/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controlplane

import (
	"context"
	"fmt"
	"io"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"syscall"
	"time"

	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	ctrllog "sigs.k8s.io/controller-runtime/pkg/log"

	"github.com/kcp-dev/multicluster-provider/envtest/internal/certs"
	"github.com/kcp-dev/multicluster-provider/envtest/internal/process"
)

var log = ctrllog.Log.WithName("controlplane")

// Kcp manages a sharded-test-server process that runs one or more kcp shards
// with a front-proxy.
type Kcp struct {
	// Path is the path to the sharded-test-server binary.
	// Discovered via BinPathFinder("sharded-test-server", ...) if empty.
	Path string

	// NumberOfShards is the total shard count (including root). Default: 1.
	NumberOfShards int

	// WorkDir is the working directory for sharded-test-server.
	// If empty, a temp dir is created and cleaned on Stop().
	WorkDir string

	// BinaryAssetsDirectory is used to locate kcp, kcp-front-proxy, and
	// cache-server binaries needed by sharded-test-server.
	BinaryAssetsDirectory string

	// StartTimeout is the maximum time to wait for the server to become ready.
	StartTimeout time.Duration

	// StopTimeout is the maximum time to wait for the server to stop.
	StopTimeout time.Duration

	// Out, Err specify where sharded-test-server should write its stdout/stderr.
	// If not specified, the output will be discarded.
	Out io.Writer
	Err io.Writer

	// Args are additional flags passed to sharded-test-server.
	Args []string

	// KubectlPath will override the default asset search path for kubectl.
	KubectlPath string

	cmd              *exec.Cmd
	workDir          string
	dirNeedsCleaning bool
}

// Start launches the sharded-test-server process and waits for it to become ready.
func (k *Kcp) Start() error {
	if k.Path == "" {
		k.Path = process.BinPathFinder("sharded-test-server", k.BinaryAssetsDirectory)
	}
	if k.NumberOfShards <= 0 {
		k.NumberOfShards = 1
	}
	if k.StartTimeout == 0 {
		k.StartTimeout = 2 * time.Minute
	}
	if k.StopTimeout == 0 {
		k.StopTimeout = 20 * time.Second
	}

	if k.workDir == "" {
		if k.WorkDir != "" {
			k.workDir = k.WorkDir
		} else {
			dir, err := os.MkdirTemp("", "kcp_envtest_")
			if err != nil {
				return fmt.Errorf("unable to create work directory: %w", err)
			}
			k.workDir = dir
			k.dirNeedsCleaning = true
		}
	}

	args := []string{ //nolint:prealloc // preallocating for three more items is premature optimization
		"--number-of-shards=" + strconv.Itoa(k.NumberOfShards),
		"--work-dir-path=" + k.workDir,
		"--quiet",
	}
	args = append(args, k.Args...)

	k.cmd = exec.Command(k.Path, args...)
	k.cmd.SysProcAttr = process.GetSysProcAttr()
	k.cmd.Stdout = k.Out
	k.cmd.Stderr = k.Err
	k.cmd.Env = k.buildEnv()

	log.Info("starting sharded-test-server", "command", k.Path, "args", args)

	if err := k.cmd.Start(); err != nil {
		return fmt.Errorf("unable to start sharded-test-server: %w", err)
	}

	if err := k.waitForReady(); err != nil {
		_ = k.Stop()
		return err
	}

	return nil
}

// Stop terminates the sharded-test-server process and cleans up the work directory.
func (k *Kcp) Stop() error {
	defer func() {
		if k.dirNeedsCleaning && k.workDir != "" {
			_ = os.RemoveAll(k.workDir)
			k.workDir = ""
		}
	}()

	if k.cmd == nil || k.cmd.Process == nil {
		return nil
	}

	// Kill the process group so all children (shards, front-proxy, cache) are terminated.
	if err := syscall.Kill(-k.cmd.Process.Pid, syscall.SIGTERM); err != nil {
		// Process may already be gone.
		if err != syscall.ESRCH {
			return fmt.Errorf("unable to signal sharded-test-server to stop: %w", err)
		}
	}

	done := make(chan error, 1)
	go func() {
		done <- k.cmd.Wait()
	}()

	select {
	case <-done:
		return nil
	case <-time.After(k.StopTimeout):
		_ = syscall.Kill(-k.cmd.Process.Pid, syscall.SIGKILL)
		return fmt.Errorf("timeout waiting for sharded-test-server to stop")
	}
}

// AdminKubeconfigPath returns the path to the admin kubeconfig generated by
// the sharded-test-server.
func (k *Kcp) AdminKubeconfigPath() string {
	return filepath.Join(k.workDir, ".kcp", "admin.kubeconfig")
}

// RESTConfig loads the admin kubeconfig and returns a *rest.Config pointing
// to the front-proxy (base context, no /clusters/ prefix).
func (k *Kcp) RESTConfig() (*rest.Config, error) {
	loader := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: k.AdminKubeconfigPath()},
		&clientcmd.ConfigOverrides{CurrentContext: "base"},
	)
	return loader.ClientConfig()
}

// User represents a Kubernetes user.
type User struct {
	Name   string
	Groups []string
}

// AuthenticatedUser contains access information for a provisioned user.
type AuthenticatedUser struct {
	cfg  *rest.Config
	kcp  *Kcp
	name string
}

// Config returns the REST config for this user.
func (u *AuthenticatedUser) Config() *rest.Config {
	return u.cfg
}

// KubeConfig returns a serialized kubeconfig for this user.
func (u *AuthenticatedUser) KubeConfig() ([]byte, error) {
	return KubeConfigFromREST(u.cfg)
}

// Kubectl returns a KubeCtl instance for this user.
func (u *AuthenticatedUser) Kubectl() (*KubeCtl, error) {
	out, err := os.CreateTemp(u.kcp.workDir, "*.kubecfg")
	if err != nil {
		return nil, fmt.Errorf("unable to create file for kubeconfig: %w", err)
	}
	defer out.Close()
	contents, err := KubeConfigFromREST(u.cfg)
	if err != nil {
		return nil, err
	}
	if _, err := out.Write(contents); err != nil {
		return nil, fmt.Errorf("unable to write kubeconfig to disk: %w", err)
	}
	kubectl := &KubeCtl{
		Path: u.kcp.KubectlPath,
	}
	kubectl.Opts = append(kubectl.Opts, fmt.Sprintf("--kubeconfig=%s", out.Name()))
	return kubectl, nil
}

// AddUser provisions a new user by issuing a client certificate from the
// kcp cluster's client CA.
func (k *Kcp) AddUser(user User, baseConfig *rest.Config) (*AuthenticatedUser, error) {
	if k.workDir == "" {
		return nil, fmt.Errorf("kcp has not been started yet")
	}

	ca, err := certs.LoadTinyCA(
		filepath.Join(k.workDir, ".kcp", "client-ca.crt"),
		filepath.Join(k.workDir, ".kcp", "client-ca.key"),
	)
	if err != nil {
		return nil, fmt.Errorf("unable to load client CA: %w", err)
	}

	clientCert, err := ca.NewClientCert(certs.ClientInfo{
		Name:   user.Name,
		Groups: user.Groups,
	})
	if err != nil {
		return nil, fmt.Errorf("unable to create client certificate for %s: %w", user.Name, err)
	}

	crt, key, err := clientCert.AsBytes()
	if err != nil {
		return nil, fmt.Errorf("unable to serialize client certificate for %s: %w", user.Name, err)
	}

	restCfg, err := k.RESTConfig()
	if err != nil {
		return nil, fmt.Errorf("unable to load base REST config: %w", err)
	}

	if baseConfig != nil {
		restCfg.QPS = baseConfig.QPS
		restCfg.Burst = baseConfig.Burst
	}
	restCfg.CertData = crt
	restCfg.KeyData = key

	return &AuthenticatedUser{
		cfg:  restCfg,
		kcp:  k,
		name: user.Name,
	}, nil
}

func (k *Kcp) waitForReady() error {
	readyFile := filepath.Join(k.workDir, ".kcp", "ready-to-test")
	ctx, cancel := context.WithTimeout(context.Background(), k.StartTimeout)
	defer cancel()

	return wait.PollUntilContextCancel(ctx, 200*time.Millisecond, true, func(ctx context.Context) (bool, error) {
		// Check if process has exited.
		if k.cmd.ProcessState != nil {
			return false, fmt.Errorf("sharded-test-server exited prematurely with code %d", k.cmd.ProcessState.ExitCode())
		}
		_, err := os.Stat(readyFile)
		return err == nil, nil
	})
}

func (k *Kcp) buildEnv() []string {
	env := os.Environ()

	// Ensure NO_GORUN is set so sharded-test-server looks for binaries in PATH
	// instead of trying `go run`.
	env = setEnv(env, "NO_GORUN", "true")

	// Build a PATH that includes the directories containing the required binaries.
	dirs := make(map[string]struct{})
	for _, name := range []string{"kcp", "kcp-front-proxy", "cache-server"} {
		binPath := process.BinPathFinder(name, k.BinaryAssetsDirectory)
		dir := filepath.Dir(binPath)
		dirs[dir] = struct{}{}
	}

	currentPath := os.Getenv("PATH")
	newPath := strings.Join(append(slices.Collect(maps.Keys(dirs)), currentPath), string(os.PathListSeparator))
	env = setEnv(env, "PATH", newPath)

	return env
}

func setEnv(env []string, key, value string) []string {
	prefix := key + "="
	for i, e := range env {
		if strings.HasPrefix(e, prefix) {
			env[i] = prefix + value
			return env
		}
	}
	return append(env, prefix+value)
}
